// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToWatchlist(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddToWatchlist'](arg1, arg2, arg3);
}

export function AnalyzeCoin(arg1) {
  return window['go']['main']['App']['AnalyzeCoin'](arg1);
}

export function ClearAPIKey() {
  return window['go']['main']['App']['ClearAPIKey']();
}

export function DeleteAlert(arg1) {
  return window['go']['main']['App']['DeleteAlert'](arg1);
}

export function EvaluateNow() {
  return window['go']['main']['App']['EvaluateNow']();
}

export function GetAlert(arg1) {
  return window['go']['main']['App']['GetAlert'](arg1);
}

export function GetAlerts() {
  return window['go']['main']['App']['GetAlerts']();
}

export function GetAnalysisHistory(arg1) {
  return window['go']['main']['App']['GetAnalysisHistory'](arg1);
}

export function GetEvalStats() {
  return window['go']['main']['App']['GetEvalStats']();
}

export function GetMarketOverview() {
  return window['go']['main']['App']['GetMarketOverview']();
}

export function GetNews() {
  return window['go']['main']['App']['GetNews']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTopCoins(arg1) {
  return window['go']['main']['App']['GetTopCoins'](arg1);
}

export function GetWatchlist() {
  return window['go']['main']['App']['GetWatchlist']();
}

export function GetWatchlistPrices() {
  return window['go']['main']['App']['GetWatchlistPrices']();
}

export function RemoveFromWatchlist(arg1) {
  return window['go']['main']['App']['RemoveFromWatchlist'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchCoins(arg1) {
  return window['go']['main']['App']['SearchCoins'](arg1);
}

export function SetAlert(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAlert'](arg1, arg2, arg3, arg4);
}

export function SetAlertEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetAlertEnabled'](arg1, arg2);
}
