// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddToWatchlist(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AnalyzeCoin(arg1:string):Promise<models.AnalysisRecord>;

export function CancelAnalysis(arg1:string):Promise<void>;

export function ClearAPIKey():Promise<void>;

export function DeleteAlert(arg1:number):Promise<void>;

export function EvaluateNow():Promise<models.EvalStats>;

export function GetAlert(arg1:string):Promise<models.PriceAlert>;

export function GetAlerts():Promise<Array<models.PriceAlert>>;

export function GetAnalysisHistory(arg1:number):Promise<Array<models.AnalysisRecord>>;

export function GetEvalStats():Promise<models.EvalStats>;

export function GetMarketOverview():Promise<models.MarketOverview>;

export function GetNews():Promise<Array<models.NewsItem>>;

export function GetSettings():Promise<models.Settings>;

export function GetTopCoins(arg1:number):Promise<Array<models.CachedPrice>>;

export function GetWatchlist():Promise<Array<models.WatchlistItem>>;

export function GetWatchlistPrices():Promise<Array<models.CachedPrice>>;

export function RemoveFromWatchlist(arg1:string):Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SearchCoins(arg1:string):Promise<Array<models.CoinSearchResult>>;

export function SetAlert(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function SetAlertEnabled(arg1:number,arg2:boolean):Promise<void>;
